# Generated by Django 4.2 on 2023-04-15 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_certificate_education_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='profile_photo',
            field=models.CharField(default=datetime.datetime(2023, 4, 15, 14, 3, 11, 153160, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=datetime.datetime(2023, 4, 15, 14, 3, 30, 969213, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='icon_link',
            field=models.CharField(default=datetime.datetime(2023, 4, 15, 14, 3, 37, 867411, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
