# Generated by Django 4.2 on 2023-04-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_header_profile_photo_project_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='description',
            new_name='icon_link',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='link',
            new_name='organization',
        ),
    ]
