# Generated by Django 4.2 on 2023-04-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_otherskill_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='experience',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='happyClients',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='projectNumber',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
