# Generated by Django 4.2 on 2023-04-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_rename_projectnumber_header_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='mail',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
