# Generated by Django 4.2 on 2023-04-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_header_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='icon_link',
            new_name='gitHub',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='link',
            new_name='linkedIn',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='name',
            new_name='stackOverFlow',
        ),
    ]
