# Generated by Django 4.2 on 2023-04-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_rename_icon_link_socialmedia_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='field',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
