# Generated by Django 4.2 on 2023-04-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_project_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='experience',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
