# Generated by Django 4.2 on 2023-04-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_workexperience_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.JSONField(),
        ),
    ]
